AWSTemplateFormatVersion: 2010-09-09

Description: This template create an Application Load Balancer

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
#      -   *** NOT USING HTTPS ON LAB SandBox ***
#        Label: 
#          default: "Certificate Arn"
#        Parameters:
#          - AcmCertificate
      - 
        Label: 
          default: "Export VPC Stack Name"
        Parameters:
          - ExportVpcStackName

      - 
        Label: 
          default: "EC2 Parameters"
        Parameters:
          - AmazonImageID
          - InstanceType
          - KeyName

Parameters:
#  AcmCertificate:  *** NOT USING HTTPS ON LAB SandBox ***
#    Description: The ARN of the AWS Certification Manager's certificate
#    Type: String

  ExportVpcStackName:
    Description: The name of the vpc stack that exports values
    Type: String

  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t1.micro
      - t2.nano
      - t2.micro
    ConstraintDescription: must be a valid EC2 instance type.

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  AmazonImageID:
    Description: The ID of the Amazon machine image (AMI)
    Type: String

Resources:
#Create an Application Load Balancer
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: MyApplicationLoadBalancer
      SecurityGroups:
        - Fn::ImportValue: !Sub ${ExportVpcStackName}-ALBSecurityGroup
      Subnets: 
        - Fn::ImportValue: !Sub ${ExportVpcStackName}-PublicSubnet1
        - Fn::ImportValue: !Sub ${ExportVpcStackName}-PublicSubnet2

##Create a Listener on Port 80
#  ALBListenerNoSslCertificate:
#    Type: 'AWS::ElasticLoadBalancingV2::Listener'
#    Properties:
#      DefaultActions:
#        - RedirectConfig:    
#            Host: '#{host}'
#            Path: '/#{path}'
#            Port: '443'
#            Protocol: HTTPS
#            StatusCode: HTTP_301
#          Type: redirect           *** NOT USING HTTPS ON LAB SandBox ***
#      LoadBalancerArn: !Ref ApplicationLoadBalancer
#      Port: 80
#      Protocol: HTTP

#Create a Listener on Port 80 / NO REDIRECT TO HTTPS ON LAB SandBox / Add TargetGroup for port 80
  ALBListenerNoSslCertificate:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref ALBTargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

##Create a Listener on Port 443 *** NOT USING HTTPS ON LAB SandBox ***
#  ALBListenerSslCertificate:
#    Type : AWS::ElasticLoadBalancingV2::Listener
#    Properties:
#      Certificates:
#        - CertificateArn: !Ref AcmCertificate
#      DefaultActions:
#        - Type: forward
#          TargetGroupArn: !Ref ALBTargetGroup
#      LoadBalancerArn: !Ref ApplicationLoadBalancer
#      Port: 443
#      Protocol: HTTPS

##Create a SSH Listener on Port 22 
#  ALBListenerSSHCertificate:
#    Type: 'AWS::ElasticLoadBalancingV2::Listener'
#    Properties:
#      DefaultActions:
#      - Type: forward
#        TargetGroupArn: !Ref ALBTargetGroup
#      LoadBalancerArn: !Ref ApplicationLoadBalancer
#      Port: 22
#      Protocol: TCP

# Create a Target Group  - Add HTTP, HTTP and SSH PORT for LAB SandBox
  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Matcher:
        HttpCode: 200,302
      Name: MyWebServers
      Port: 80
      Protocol: HTTP
      Targets:
        - Id: !Ref EC2Instance1
          Port: 80
        - Id: !Ref EC2Instance2
          Port: 80
      TargetType: instance
      UnhealthyThresholdCount: 5
      VpcId:
        Fn::ImportValue: !Sub ${ExportVpcStackName}-VPC

  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId:
        Fn::ImportValue: !Sub ${ExportVpcStackName}-PrivateSubnet1
      SecurityGroupIds:
        - Fn::ImportValue: !Sub ${ExportVpcStackName}-WebServerSecurityGroup
      KeyName: !Ref KeyName
      ImageId: !Ref AmazonImageID 
      Tags:
        - Key: Name
          Value: EC2 | Private Subnet 1
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            # Update the package repository
            sudo yum update -y
            # Install Apache web server
            sudo yum install -y httpd
            # Start the Apache service
            sudo systemctl start httpd
            # Enable Apache to start on boot
            sudo systemctl enable httpd
            # Simple index.html page
            echo "<h1>Hello from CloudFormation EC2 Web Server 1!</h1>" | sudo tee /var/www/html/index.html
            echo "<p>This instance is on a load balancer and accessible via SSH.</p>" | sudo tee -a /var/www/html/index.html            

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId:
        Fn::ImportValue: !Sub ${ExportVpcStackName}-PrivateSubnet2
      SecurityGroupIds:
        - Fn::ImportValue: !Sub ${ExportVpcStackName}-WebServerSecurityGroup
      KeyName: !Ref KeyName
      ImageId: !Ref AmazonImageID 
      Tags:
        - Key: Name
          Value: EC2 | Private Subnet 2
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            # Update the package repository
            sudo yum update -y
            # Install Apache web server
            sudo yum install -y httpd
            # Start the Apache service
            sudo systemctl start httpd
            # Enable Apache to start on boot
            sudo systemctl enable httpd
            # Simple index.html page
            echo "<h1>Hello from CloudFormation EC2 Web Server 2!</h1>" | sudo tee /var/www/html/index.html
            echo "<p>This instance is on a load balancer and accessible via SSH.</p>" | sudo tee -a /var/www/html/index.html            

Outputs:
# Export Target Group
  ALBTargetGroup:
    Description: Webserver target group
    Export:
      Name: !Sub ${AWS::StackName}-ALBTargetGroup
    Value: !Ref ALBTargetGroup

# Export Application Load Balancer Dns Name
  ApplicationLoadBalancerDnsName:
    Description: Application Load Balancer DNS Name
    Export:
      Name: !Sub ${AWS::StackName}-ApplicationLoadBalancerDnsName
    Value: !GetAtt ApplicationLoadBalancer.DNSName

# Export Application Load Balancer Zone ID
  ApplicationLoadBalancerZoneID:
    Description: Application Load Balancer Canonical Hosted Zone ID
    Export:
      Name: !Sub ${AWS::StackName}-ApplicationLoadBalancerZoneID
    Value: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID